title: Jpparks Group - Japanese Garden design and construction company.
email: quang80212@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Quang Hoang # add your name
author-pic: Quang-Hoang.jpg
about-author: My name is Quang Hoang. 
# Contact links
email: quang80212@gmail.com # Add your Email address
phone: (+84) # Add your Phone number
website: http://jpparks.com/ # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: artemsheludko # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle
facebook: japanparks # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: thomasthevinh # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 10
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
